# Generated by Django 5.2.8 on 2025-11-22 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('expired', 'Expired'), ('returned', 'Returned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fine',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='books.bookloan'),
        ),
    ]
