# Generated by Django 5.2.8 on 2025-11-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('reader', 'Reader')], default='librarian', max_length=50),
            preserve_default=False,
        ),
    ]
